### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by F1R3L1GHT** [jshttp/cookie#116]
```js
app.get("/", function(req, res){
      res.setHeader('Set-Cookie', cookie.serialize('name','lolxd', {
      httpOnly: true,
      maxAge: 60 * 60 * 24 * 7 // 1 week
    }));
      var cookies = cookie.parse(req.headers.cookie || '');

  // Get the visitor name set in the cookie
  var name = cookies.name;
}) 
```
yeh this is my code, used the example with express, logs 'undefined'.

**Comment by dougwilson** [comment]
Very strange. Is your web browser sending the cookie  back to the server? Can you provide a complete app with the steps to reproduce? I just tried the example from the readme in chrome and it is working fine, so if we can figure what what the difference is, that will be the best bet.

**Comment by F1R3L1GHT** [comment]
I currently am not sure, as I have a chromebook borrowed from my school. Here is the entire code:
const express = require('express');
const cookie = require('cookie');
const app = express();

app.get('/', function(req, res) {
res.setHeader('Set-Cookie', cookie.serialize('name','lolxd', {
httpOnly: true,
maxAge: 60 * 60 * 24 * 7 // 1 week
}));
var cookies = cookie.parse(req.headers.cookie || '');

// Get the visitor name set in the cookie
var name = cookies.name;
})

**Comment by F1R3L1GHT** [comment]
*The chromebook cannot open console/view cookies*

**Comment by dougwilson** [comment]
Hi @F1R3L1GHT thanks for that. I am seeing it work just fine in Chrome, at lest. Based on your app, the reason it does not work is because you never send a response in order for the web browser to set the cookie. Your setHeader queues a response header to send back to the web browser, and you should call `res.send()` at some point.

Then your cookie will be visible on the _next_ request to the web server.
