### ISSUE TITLE
maxAge is ignored

### ISSUE THREAD

**Issue by Rashe** [jshttp/cookie#168]
I try to set maxAge for cookie, but no matter what I do the expiration is always "Session"

The frontend and backend are not on the same domain. 

Btw, it works on localhost

My code: 

```js
async function login(req, res) {
  try {
    const { email, password } = req.body
    const { token, refreshToken, user } = await authService.login({ email, password })

    res.setCookie("refreshToken", refreshToken, {
  httpOnly: true,
  sameSite: "None",
  secure: true,
  path: "/",
  signed: true,
  maxAge: 30 * 24 * 60 * 60
}).send({ accessToken: token, user })
  } catch (e) {
    console.error(e)
    return res.status(401).send({ error: "Unauthorized" })
  }
}
```

**Comment by blakeembrey** [comment]
I'm going to close this out since `maxAge` is working based on the test suite and there's no enough to debug in this issue. Where is `res.setCookie` coming from? Is it passing through `maxAge` to this library correctly? It might be worth filing an issue with the upstream library you are using for `res.setCookie`.
