### ISSUE TITLE
What's the purpose of the `options.sameSite` branch of ternary in serialize?

### ISSUE THREAD

**Issue by jonchurch** [jshttp/cookie#206]
What's the purpose of the `options.sameSite` branch of ternary in serialize?

When `options.priority` is not a string, it will use `options.sameSite`. There's no overlap in the types between the two, so we'd hit the default and throw. Was there meant to be overlap or is this a typo?
https://github.com/jshttp/cookie/blob/408c2b40c6c5783fcfae619d30e8427e9c96a2db/src/index.ts#L314
```ts
  if (options.priority) {
    const priority =
      typeof options.priority === "string"
        ? options.priority.toLowerCase()
        : options.sameSite; // typo?
    switch (priority) {
      case "low":
        str += "; Priority=Low";
        break;
      case "medium":
        str += "; Priority=Medium";
        break;
      case "high":
        str += "; Priority=High";
        break;
      default:
        throw new TypeError(`option priority is invalid: ${options.priority}`);
    }
  }
```

**Comment by blakeembrey** [comment]
In the old code it was for the error message, this was a bad copy and paste when I re-added case insensitivity: https://github.com/jshttp/cookie/blob/e206fd539de8a23f4bca1cc2a86551ba0cdd8a51/index.js#L254-L269

Honestly, throwing `options.priority` instead of `priority` is a bit nicer and should not have tried to copy the same fallback behavior in the previous code.
