### ISSUE TITLE
Update serialize to accept a object of key/values.

### ISSUE THREAD

**Issue by jgornick** [jshttp/cookie#30]
The serialize method should be updated to accept an object of key/values and serialize to a cookie string. This would make the serialize/parse methods complement each other.

**Comment by defunctzombie** [comment]
I could agree with that. PR would be appreciated.

**Comment by frogcjn** [comment]
any updates?

**Comment by jgornick** [comment]
@frogcjn It looks like #47 is a PR for this functionality.

@dougwilson This issue should be closed and marked as a duplicate, right?

**Comment by dougwilson** [comment]
> This issue should be closed and marked as a duplicate, right?

Why? This issue was opening prior to that PR, so if anything should be closed for being a duplicate, it should be the PR, right?

**Comment by jgornick** [comment]
@dougwilson I didn't see that the PR (#47) referenced this issue in the description:

> Resolves #30

So, in my view, yes this issue should stay open until the PR has been merged.

**Comment by danday74** [comment]
when is this getting merged?

**Comment by gurupras** [comment]
I have another use-case for `Cookie.serialize` to accept objects that goes beyond `Set-Cookie`, which you may not have considered.

I'm building a WebExtension that modifies the `Cookie` header of requests going out of the browser. This library has been very useful in parsing the cookies into objects, but isn't as convenient to serialize them back to a single `Cookie` line.

I realize that mine is probably an edge-case, but I found it surprising that the parse, and serialize do not compliment one another. i.e, `Cookie.serialize(Cookie.parse(str)) === str`

**Comment by dougwilson** [comment]
Hi @gurupras , I don't think this issue will help you, though, because this proposal will still not make them compliment one another as you're expecting, as `Cookie.serialize` creates `Set-Cookie` header format and not the `Cookie` header format. Accepting an object (as in this proposal) would not change that; it sounds like you are make a separate request from the one in this issue.

**Comment by export-mike** [comment]
I have wanted this feature recently and updated it to create a new PR against the current state of the main branch.

#119

**Comment by blakeembrey** [comment]
Closing this out for now, but if there's interest I could see a new method being added for this functionality. It doesn't make a lot of sense to alter the existing `serialize` signature because it's producing a `Set-Cookie`, but I can imagine two different approaches:

1. Wanting an object to format into a `Cookie` header (this is different to `Set-Cookie`).
2. Wanting an object + options to format into multiple `Set-Cookie` headers, i.e. an array.

If someone has strong feelings on how it should work and what it's solving for you, feel free to open a new issue.
