### ISSUE TITLE
encoding/decoding strangeness

### ISSUE THREAD

**Issue by tamagokun** [jshttp/cookie#34]
I am using `cookie` as an underlying module to handle cookies for session handling. Specifically `express-session` and `connect-redis` as a store.

When running the app locally (Mac OSX, nodemon) everything works fantastically.

When running the app on a test environment (Ubuntu, nginx) the cookie isn't getting url decoded somewhere down the line. I'm not sure if this is up to the browser to decode, or if the server needs to decode the Set-Cookie header before sending. So, sessions typically will be prefixed with `s:` which is the result when running locally. In the test environment it is `s%3A`. On the server side, everything seems to work just fine, but I am trying to do some cors requests _with_ credentials and nothing is working because it is expecting the cookie to start with s: and not s%3A.

I can't figure out where in the process this is happening, so it is entirely possible that I am creating this issue on the wrong repo, but I did notice other url encoding issues here, so maybe someone has had a similar problem and can share some knowledge.

_note:_ I am looking at the cookie value in the browser using Chrome's resources tab.

**Comment by dougwilson** [comment]
The bug is just in the way you are doing things; a cookie's value is _opaque_ and so browser do no decoding anywhere. The problem is there are various values that _cannot be in the cookie header_, like the `:` character. The question comes down to: how do we convey a `:` character? The RFC suggests even just base64-encoding the entire value, but that's crazy. We just URL-encode the characters we are not allowed to use.

You'll have to URL decode the header yourself where ever you're reading it. Without more detail about your code and architecture, it's hard to say, but what it comes down to is a bug in your code.

**Comment by tamagokun** [comment]
Awesome. Thanks!
