### ISSUE TITLE
var cookie = require("cookie");

### ISSUE THREAD

**Issue by ORESoftware** [jshttp/cookie#35]
I got this lovely one today

```
var cookie = require("cookie");

node_modules/cookie/index.js:38   var pairs = str.split(/; */);                  
^ TypeError: Cannot read property 'split' of undefined
```

it occurred inside of this socket.io handshake hook

```javascript
io.use(function (socket, next) {
        var handshakeData = socket.request;
        if (handshakeData.headers.cookie) {
            handshakeData.cookie = cookie.parse(handshakeData.headers.cookie); //error here
            handshakeData.sessionID = cookie.parse(handshakeData.cookie['express.sid'], 'foo'); //error here
            if (handshakeData.cookie['express.sid'] == handshakeData.sessionID) {
                return next('Cookie is invalid.', false);
            }
        } else {
            return next('No cookie transmitted.', false);
        }
        console.log('user with socket.id=',socket.id,'has authenticated successfully.');
       return next(null, true);
    });
```

**Comment by dougwilson** [comment]
The reason is because `handshakeData.headers.cookie` is not a string. I can change it, but all we're going to do is throw a different error, so you'll still have to change your code, ultimately, to not call the `.parse` method with invalid data (i.e. it needs to be a cookie header to parse, rather than `undefined`).

**Comment by ORESoftware** [comment]
ok, so I have to check if (handshakeData.cookie['express.sid']) is undefined?

i think we are talking about handshakeData.cookie['express.sid'] not handshakeData.headers.cookie.

if you were writing the code above, what would you do if handshakeData.cookie['express.sid'] is undefined?

**Comment by ORESoftware** [comment]
what I did for now was just check for both, and give the same result

like so

```javascript
if (handshakeData.headers.cookie && handshakeData.cookie['express.sid']) {
```

**Comment by ORESoftware** [comment]
well, I did that, then I got this:

```javascript
/Users/amills001c/WebstormProjects/ORESoftware/sc-admin-ui-express/socketio.js:15
        if (handshakeData.headers.cookie && handshakeData.cookie['express.sid'
                                                                ^
TypeError: Cannot read property 'express.sid' of undefined
    at Array.<anonymous> (/Users/amills001c/WebstormProjects/ORESoftware/sc-admin-ui-express/socketio.js:15:65)
```

**Comment by ORESoftware** [comment]
importantly, that error is in socket.io, not your lib

**Comment by ORESoftware** [comment]
also, if you could briefly explain why this check is the right thing to do, that would be awesome, this doesn't make sense to me

```javascript
 if (handshakeData.cookie['express.sid'] == handshakeData.sessionID) {
                return next('Cookie is invalid.', false);
            }
```

why should the cookie be in invalid in that case?

**Comment by dougwilson** [comment]
I am unsure of what your code is even doing, especially since I've never used socket.io. Can you provide full code I can run to reproduce the issue?

The only issue I'm talking about is specifically the since error you posted: `TypeError: Cannot read property 'split' of undefined`. The easiest way to prevent is to use
```js
handshakeData.cookie = cookie.parse(handshakeData.headers.cookie || '')
handshakeData.sessionID = cookie.parse(handshakeData.cookie['express.sid'] || '', 'foo')
```
but I cannot speak for what you are trying to do, only help prevent you from passing in `undefined` to this library, which is invalid.
