### ISSUE TITLE
Issue with encodeURIComponent for corrupted characters

### ISSUE THREAD

**Issue by landonsilla** [jshttp/cookie#51]
I've had a very rare problem in my express application that was causing the process to crash.  I tracked the issue down to an incoming cookie that was corrupted/incomplete by the client ... I think.  After read 
https://mathiasbynens.be/notes/javascript-unicode, I found that some more obscure utf characters actually have a length property of 2, and then if you try to access the first character in them, javascript flips out. Example:

    '𠮷'.length             // is 2
    '𠮷'[0]                 // invalid character

Now, if I try to set an outgoing cookie to that value, express crashes.

	var express = require('express');
	var app = express();
	
	app.get('/', function (req, res) {
		setTimeout(function(){
			res.cookie('myCookie','𠮷'[0]) // let's say this came in that way and I'm just writing it back
			res.send('Hello World!');	
		},1)
	});
	
	
	app.listen(8123, function () {
		console.log('Example app listening on port 8123!');
	})

Note that the setTimeout is important to crash the process. Any sort of async callback will likely do the trick.

Internally, there is a call to `encodeURIComponent` to set the cookie, and it is effectively doing `encodeURIComponent('𠮷'[0])` which is bad. 

What is the solution here? Wrap that call in a try catch so that it will fail gracefully?

**Comment by dougwilson** [comment]
Hi @landonsilla , since this module is a sync interface, not a callback-style interface, it is expected that the functions we provide will throw on invalid input. You will need to either use `domain`s or `try ... catch` in your code, or ensure that in some way a `try` block in in the stack tree when you call methods to this module if you don't want it to crash the process. This is a standard Node.js "issue".
