### ISSUE TITLE
parsing set-cookie headers

### ISSUE THREAD

**Issue by danielb2** [jshttp/cookie#58]
Is there any way to get Cookie.parse to be able to parse a set-cookie ?

Example: 

`visitor=35396244; Domain=.blah.com; Expires=Fri, 06-Jul-2018 00:23:32 GMT; Path=/`

```
{
    visitor: '35396244',
    Domain: '.blah.com',
    Expires: 'Fri, 06-Jul-2018 00:23:32 GMT',
    Path: '/'
}
```

but here there's no deterministic way of saying that `visitor` is the name of the cookie

Or is there another recommended npm module to do this?

**Comment by danielb2** [comment]
I'll try this: https://www.npmjs.com/package/set-cookie-parser

**Comment by wesleytodd** [comment]
For reference, this is a duplicate: #50 & #12

**Comment by dougwilson** [comment]
Yes, this module only handles the `Cookie` header, as you discovered, and @wesleytodd pointed out :) There has been a little discussion on the topic, but didn't really go anywhere. Ideally I like to make a module that does only one thing. This module was donated as-is and maintenance was taken over as it is for now. To me, I personally find it weird to have something parse one header and stringify a different header. I understand why the original author did this, because the way it is written now is the exact use-case that would work on the server-side, so really haven't changed it.

In the ideal world, I would say this module should only parse the `Cookie` header and also only stringify the `Cookie` header. We are currently in the half-state of parsing `Cookie`, but stringifying `Set-Cookie`, I know. But as you can see, if I were to move in one direction from the current state, it would be in the ideal state, which does not include adding `Set-Cookie` parsing.

The `set-cookie-parser` module looks like a fine module to use.
